# Generated by Django 4.0.4 on 2022-09-17 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='yr',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1875)]),
        ),
        migrations.AlterField(
            model_name='electriccar',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='electriccar',
            name='yr',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1875)]),
        ),
        migrations.AlterField(
            model_name='iceCar',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='iceCar',
            name='yr',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1875)]),
        ),
    ]
