# Generated by Django 4.0.4 on 2022-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0002_alter_automobile_id_alter_automobile_yr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobile',
            old_name='yr',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='electriccar',
            old_name='yr',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='icecar',
            old_name='yr',
            new_name='year',
        ),
        migrations.AddField(
            model_name='automobile',
            name='topSpeed',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='automobile',
            name='zeroToSixty',
            field=models.FloatField(default=99),
        ),
        migrations.AddField(
            model_name='electriccar',
            name='range',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='icecar',
            name='displacement',
            field=models.FloatField(default=0.1),
        ),
    ]
