# Generated by Django 4.2.2 on 2023-08-28 23:00
"""We are transfering data from the ICE cars and Electric cars tables to the Automobiles table.
   The reason for this consolidation is that it seems weird to have three separate tables where
   there is some overlap in data across different tables.\n
   
   So the plan is to delete the ICE cars and Electric cars models after migrating the data. Then, 
   I will create a new model/table called 'personal computers' and put some data in there to  
   have some variety."""

from django.db import migrations

def copy_data(apps, schema_editor):
    # Get the models for the two tables
    ICEcars = apps.get_model('helloWorld', 'icecar')
    
    DestinationModel = apps.get_model('helloWorld', 'automobile')

    # Copy the data from the source table to the destination table
    for row in ICEcars.objects.all():
        new_row = DestinationModel()
        new_row.year = row.year
        new_row.make = row.make
        new_row.model = row.model
        new_row.vehicleType = row.vehicleType
        new_row.gasOrElectric = 'gas'
        new_row.topSpeed = 1
        new_row.zeroToSixty = 99
        new_row.displacement = row.displacement  # set the value of the missing field to the corresponding value in the source table
        new_row.range = 1
        new_row.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0006_add_displacement_to_automobile'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
