# Generated by Django 4.2.2 on 2023-08-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0008_electriccar_data_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='range',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='topSpeed',
            field=models.FloatField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='automobile',
            name='zeroToSixty',
            field=models.FloatField(default=99, null=True),
        ),
    ]
