# Generated by Django 4.2.2 on 2023-09-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloWorld', '0010_alter_automobile_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='gasOrElectric',
            field=models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('hydrogen', 'Hydrogen'), ('other', 'Other')], max_length=11),
        ),
    ]
